# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de52b3f5a9d7691d20fc6ba2fe61409e8ebf231dc806eedc76f0c36504c44bdead63c17c87680108cd877b07b72c4f033868b29c576da181b3c268a81afb0e7

test:
  secret_key_base: c3085260e1b3931789d9bc632914a4b9c7b2c4d5fc8be8e197854ae4a0d7c36d819de28a2bb56274d16b9aefbe32a5b0e20b9b7d4497b7d6edb55283295e16ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
